apiVersion: v1
kind: Service
metadata:
  name: my-devops-service
spec:
  type: NodePort        # Opens a specific port on the node to the outside world
  selector:
    app: my-devops-app  # This must match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80          # The service port
      targetPort: 5000   # The container port (where your Nginx/app is listening)